# This file was generated by GoReleaser. DO NOT EDIT.
cask "llamavm" do
  version "1.1.7"

  on_macos do
    on_arm do
      sha256 "5ee3f813c168683da7c38a9cd1618c053c1bba9004d7f8365d2f189476b82b57"
      url "https://github.com/gregmundy/llamavm/releases/download/v#{version}/llamavm_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "llamavm"
  desc "Version manager for llama.cpp on Apple Silicon"
  homepage "https://github.com/gregmundy/llamavm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llamavm"
  binary "llamavm-shim"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    llamavm needs its shims directory on PATH. Add this to your shell rc:

      export PATH="$HOME/.llamavm/shims:$PATH"

    Then install a llama.cpp version:

      llamavm install latest
      llamavm doctor
  EOS
end
