# This file was generated by GoReleaser. DO NOT EDIT.
cask "llamavm" do
  version "1.1.6"

  on_macos do
    on_arm do
      sha256 "3a07a546eff8885261ec27f43e4655c109f37aa794fc1ced64be3ca8361830af"
      url "https://github.com/gregmundy/llamavm/releases/download/v#{version}/llamavm_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "llamavm"
  desc "Version manager for llama.cpp on Apple Silicon"
  homepage "https://github.com/gregmundy/llamavm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llamavm"
  binary "llamavm-shim"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    llamavm needs its shims directory on PATH. Add this to your shell rc:

      export PATH="$HOME/.llamavm/shims:$PATH"

    Then install a llama.cpp version:

      llamavm install latest
      llamavm doctor
  EOS
end
