# This file was generated by GoReleaser. DO NOT EDIT.
cask "llamactl" do
  version "1.4.4"

  on_macos do
    on_arm do
      sha256 "6c4666010adefb7b86ec2ea49cf2052aa3bf149fdbd1764ba8456090d49bd936"
      url "https://github.com/gregmundy/llamactl/releases/download/v#{version}/llamactl_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "llamactl"
  desc "Run llama.cpp on Apple Silicon"
  homepage "https://github.com/gregmundy/llamactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llamactl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Verify your environment after install:

      llamactl doctor

    Add your first model:

      llamactl add qwen2.5-3b-instruct
  EOS
end
