# This file was generated by GoReleaser. DO NOT EDIT.
cask "llamactl" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "523deac805e2d4d54d9fdf150a8ec361ec31f3271ce9bb4c5b9188a3ebbfe418"
      url "https://github.com/gregmundy/llamactl/releases/download/v#{version}/llamactl_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "llamactl"
  desc "Run llama.cpp on Apple Silicon"
  homepage "https://github.com/gregmundy/llamactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llamactl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Verify your environment after install:

      llamactl doctor

    Add your first model:

      llamactl add qwen2.5-3b-instruct
  EOS
end
