# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llamavm < Formula
  desc "Version manager for llama.cpp on Apple Silicon"
  homepage "https://github.com/gregmundy/llamavm"
  version "1.1.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/gregmundy/llamavm/releases/download/v1.1.2/llamavm_1.1.2_darwin_arm64.tar.gz"
    sha256 "06a09d57b4af56aa63fbf489c9d3aeb873b0619ff8557522a023d0227ff176bb"

    define_method(:install) do
      bin.install "llamavm"
      bin.install "llamavm-shim"
    end
  end

  def caveats
    <<~EOS
      llamavm needs its shims directory on PATH. Add this to your shell rc:

        export PATH="$HOME/.llamavm/shims:$PATH"

      Then install a llama.cpp version:

        llamavm install latest
        llamavm doctor
    EOS
  end

  test do
    assert_match "llamavm version", shell_output("#{bin}/llamavm --version")
  end
end
